import {
  ManagedApplication,
  ManagedAppId,
  ManagedFeature,
  ManagedPage,
  PageStatus,
} from './page-feature-management.models';

type FeatureSpec = [string, string, string, ('enabled' | 'disabled')?];

const seededAt = 'Seeded inventory';

function buildFeatures(pageId: string, specs: FeatureSpec[]): ManagedFeature[] {
  return specs.map(([id, name, description, status = 'enabled']) => ({
    id: `${pageId}-${id}`,
    name,
    description,
    status,
  }));
}

function page(
  appId: ManagedAppId,
  id: string,
  name: string,
  route: string,
  description: string,
  features: FeatureSpec[],
  status: PageStatus = 'enabled',
  options: Partial<
    Pick<ManagedPage, 'protected' | 'redirected' | 'legacy'>
  > = {},
): ManagedPage {
  return {
    id,
    appId,
    name,
    description,
    route,
    status,
    lastUpdated: seededAt,
    features: buildFeatures(id, features),
    ...options,
  };
}

export const PAGE_FEATURE_APPS: ManagedApplication[] = [
  {
    id: 'vendor-app',
    name: 'Vendor App',
    description:
      'Vendor workspace for catalog, orders, inventory, payouts, support, and store operations.',
    icon: 'VA',
    color: 'green',
    pages: [
      page(
        'vendor-app',
        'vendor-login',
        'Login',
        '/login',
        'Vendor authentication entry point.',
        [
          [
            'credential-login',
            'Credential login',
            'Username and password login with validation.',
          ],
          [
            'force-password-change',
            'Force password change',
            'Redirects vendors who must update their password.',
          ],
          [
            'auth-errors',
            'Authentication errors',
            'Shows invalid credential and session errors.',
          ],
        ],
        'enabled',
      ),
      page(
        'vendor-app',
        'vendor-register',
        'Register',
        '/register',
        'Vendor onboarding and business registration.',
        [
          [
            'registration-wizard',
            'Registration wizard',
            'Step-by-step vendor account creation.',
          ],
          [
            'store-details',
            'Store and business details',
            'Captures public store and legal business information.',
          ],
          [
            'location-picker',
            'Map and location selection',
            'Collects address and coordinates.',
          ],
          [
            'identity-checks',
            'Identity checks',
            'Captures verification information.',
          ],
          [
            'submit-approval',
            'Submit for approval',
            'Sends registration for admin review.',
          ],
        ],
      ),
      page(
        'vendor-app',
        'vendor-change-password',
        'Change Password',
        '/change-password',
        'Vendor password update screen.',
        [
          [
            'current-password',
            'Current password validation',
            'Verifies the current password before saving.',
          ],
          [
            'new-password',
            'New password validation',
            'Validates strength and confirmation.',
          ],
          [
            'redirect',
            'Redirect after update',
            'Returns vendor to the correct workspace.',
          ],
        ],
        'enabled',
        { protected: true },
      ),
      page(
        'vendor-app',
        'vendor-pending-approval',
        'Pending Approval',
        '/pending-approval',
        'Approval status page for vendors awaiting review.',
        [
          [
            'approval-state',
            'Approval state',
            'Displays current vendor approval status.',
          ],
          [
            'status-refresh',
            'Poll and refresh status',
            'Checks whether approval has changed.',
          ],
          [
            'approved-redirect',
            'Approved redirect',
            'Moves approved vendors into the dashboard.',
          ],
        ],
        'enabled',
        { protected: true },
      ),
      page(
        'vendor-app',
        'vendor-dashboard',
        'Dashboard',
        '/',
        'Operations overview and first-time setup guidance.',
        [
          [
            'kpi-cards',
            'KPI cards',
            'Shows revenue, orders, inventory, and operations metrics.',
          ],
          [
            'operations-summary',
            'Operations summary',
            'Summarizes store readiness and open tasks.',
          ],
          [
            'onboarding-checklist',
            'Onboarding checklist',
            'Guides new vendors through setup.',
          ],
          [
            'store-toggle',
            'Store open or closed toggle',
            'Controls whether the store accepts orders.',
          ],
          ['stock-prompts', 'Stock prompts', 'Highlights inventory issues.'],
          [
            'recent-activity',
            'Recent orders and products',
            'Shows current operational activity.',
          ],
        ],
        'enabled',
        { protected: true },
      ),
      page(
        'vendor-app',
        'vendor-live-orders',
        'Live Orders',
        '/live-orders',
        'Fast operational view for active orders.',
        [
          ['auto-load', 'Auto-load live orders', 'Refreshes the live queue.'],
          [
            'start-preparing',
            'Start preparing',
            'Moves orders into preparation.',
          ],
          ['mark-ready', 'Mark ready', 'Marks packed orders ready for pickup.'],
          [
            'open-details',
            'Open details',
            'Navigates to the full order detail page.',
          ],
        ],
        'enabled',
        { protected: true },
      ),
      page(
        'vendor-app',
        'vendor-inventory',
        'Inventory',
        '/inventory',
        'Inventory health and stock adjustment workspace.',
        [
          [
            'health-filters',
            'Health filters',
            'Filters low stock, paused, missing photos, and readiness states.',
          ],
          ['stock-edits', 'Stock edits', 'Updates visible stock values.'],
          ['save-stock', 'Save stock', 'Persists stock changes.'],
          [
            'pause-availability',
            'Pause or unpause availability',
            'Controls whether products can be ordered.',
          ],
          [
            'product-cta',
            'Product CTA',
            'Guides vendors to add products when inventory is empty.',
          ],
        ],
        'enabled',
        { protected: true },
      ),
      page(
        'vendor-app',
        'vendor-products',
        'Products',
        '/products',
        'Vendor product catalog management.',
        [
          ['search', 'Search', 'Finds products by name, SKU, or catalog data.'],
          [
            'status-filters',
            'Status filters',
            'Filters products by approval, stock, and readiness.',
          ],
          ['pagination', 'Pagination', 'Pages through product records.'],
          ['auto-reload', 'Auto reload', 'Refreshes after product mutations.'],
          [
            'health-modal',
            'Health and fix modal',
            'Explains product readiness problems.',
          ],
          [
            'submit-approval',
            'Submit for approval',
            'Sends changed products to admin review.',
          ],
          [
            'edit-delete',
            'Edit and delete',
            'Opens edit flows and removes records where allowed.',
          ],
        ],
        'enabled',
        { protected: true },
      ),
      page(
        'vendor-app',
        'vendor-product-new',
        'New Product',
        '/products/new',
        'Creates vendor variants from approved master catalog items.',
        [
          [
            'catalog-search',
            'Catalog search',
            'Searches approved catalog items.',
          ],
          [
            'catalog-filter',
            'Catalog filters',
            'Filters by category or status when available.',
          ],
          [
            'catalog-select',
            'Catalog select and remove',
            'Adds and removes selected catalog items.',
          ],
          [
            'variant-drafts',
            'Variant drafts',
            'Creates editable drafts from selected catalog items.',
          ],
          [
            'variant-edit',
            'Edit variants',
            'Captures price, inventory, packaging, delivery, and catalog details.',
          ],
          [
            'duplicate-remove',
            'Duplicate and remove',
            'Duplicates or removes variant drafts.',
          ],
          [
            'save-draft',
            'Save draft',
            'Saves unfinished product data where supported.',
          ],
          [
            'review',
            'Review',
            'Shows validation and summary before submission.',
          ],
          [
            'submit-approval',
            'Submit approval',
            'Submits variants for admin approval.',
          ],
        ],
        'enabled',
        { protected: true },
      ),
      page(
        'vendor-app',
        'vendor-product-edit',
        'Product Edit',
        '/products/:id/edit',
        'Redesigned product edit form for existing vendor products.',
        [
          [
            'load-product',
            'Load by ID',
            'Loads the selected product from route params.',
          ],
          [
            'selling-controls',
            'Selling controls',
            'Updates price, stock, status, and delivery controls.',
          ],
          [
            'catalog-details',
            'Catalog details',
            'Edits fields that may require admin review.',
          ],
          [
            'attributes',
            'Product attributes',
            'Updates tags, flags, packaging, and shelf life.',
          ],
          ['save-draft', 'Save draft', 'Saves draft updates where available.'],
          [
            'save-changes',
            'Save changes',
            'Persists product changes through vendor APIs.',
          ],
        ],
        'enabled',
        { protected: true },
      ),
      page(
        'vendor-app',
        'vendor-catalog-requests',
        'Catalog Requests',
        '/catalog-requests',
        'Requests new master catalog items.',
        [
          ['create-request', 'Create request', 'Starts a catalog request.'],
          [
            'add-remove-items',
            'Add and remove items',
            'Builds request line items.',
          ],
          ['submit-request', 'Submit request', 'Sends request to admins.'],
          [
            'history-status',
            'History and status',
            'Tracks pending and reviewed requests.',
          ],
        ],
        'enabled',
        { protected: true },
      ),
      page(
        'vendor-app',
        'vendor-orders',
        'Orders',
        '/orders',
        'Order list and lifecycle management.',
        [
          ['order-list', 'Order list', 'Loads vendor orders.'],
          ['status-filter', 'Status filter', 'Filters by order status.'],
          ['search', 'Search', 'Finds orders by customer or order number.'],
          ['pagination', 'Pagination', 'Pages through order history.'],
          ['auto-reload', 'Auto reload', 'Refreshes the order list.'],
          [
            'status-updates',
            'Status updates',
            'Moves orders through vendor lifecycle states.',
          ],
        ],
        'enabled',
        { protected: true },
      ),
      page(
        'vendor-app',
        'vendor-order-detail',
        'Order Detail',
        '/orders/:id',
        'Full vendor order detail and delivery search controls.',
        [
          ['details', 'Details', 'Shows customer, items, payment, and status.'],
          ['status-changes', 'Status changes', 'Updates order status.'],
          ['cancellation', 'Cancellation', 'Handles order cancellation.'],
          [
            'delivery-search',
            'Delivery search',
            'Starts or cancels delivery partner search.',
          ],
          ['pickup-otp', 'Pickup OTP', 'Verifies delivery pickup handoff.'],
          ['invoice-download', 'Invoice download', 'Downloads order invoices.'],
          [
            'tracking-map',
            'Map and tracking',
            'Displays delivery assignment tracking.',
          ],
        ],
        'enabled',
        { protected: true },
      ),
      page(
        'vendor-app',
        'vendor-order-prep',
        'Order Prep',
        '/orders/:id/prep',
        'Focused preparation checklist for a single order.',
        [
          ['prep-checklist', 'Prep checklist', 'Shows packable order lines.'],
          [
            'toggle-packed',
            'Toggle packed items',
            'Marks line items as packed.',
          ],
          ['start-preparing', 'Start preparing', 'Begins preparation.'],
          ['mark-ready', 'Mark ready', 'Marks order ready for pickup.'],
          [
            'cancel-search',
            'Cancel delivery search',
            'Cancels active partner search.',
          ],
          ['verify-otp', 'Verify pickup OTP', 'Confirms handoff.'],
        ],
        'enabled',
        { protected: true },
      ),
      page(
        'vendor-app',
        'vendor-analytics',
        'Analytics',
        '/analytics',
        'Sales and settlement reporting.',
        [
          ['revenue', 'Revenue analytics', 'Shows sales performance.'],
          ['date-range', 'Date range', 'Filters report periods.'],
          ['top-products', 'Top products', 'Ranks product performance.'],
          [
            'settlement-summary',
            'Settlement summary',
            'Summarizes payouts and fees.',
          ],
          [
            'empty-guidance',
            'Empty guidance',
            'Explains when insights will appear.',
          ],
        ],
        'enabled',
        { protected: true },
      ),
      page(
        'vendor-app',
        'vendor-payouts',
        'Payments and Payouts',
        '/payouts',
        'Vendor payout and settlement workspace.',
        [
          ['payout-list', 'Payout list', 'Lists payout records.'],
          [
            'status-tabs',
            'Status tabs',
            'Filters pending, scheduled, paid, failed, and ledger states.',
          ],
          [
            'approve-decline',
            'Approve or decline',
            'Supports review actions when available.',
          ],
          ['verify-credit', 'Verify credit', 'Marks credited payouts.'],
          [
            'invoice-download',
            'Invoice download',
            'Downloads payout documents.',
          ],
          [
            'setup-guidance',
            'Setup guidance',
            'Explains payout readiness and missing setup.',
          ],
        ],
        'enabled',
        { protected: true },
      ),
      page(
        'vendor-app',
        'vendor-promotions',
        'Promotions',
        '/promotions',
        'Coupon creation and usage tracking.',
        [
          ['coupon-list', 'Coupon list', 'Displays vendor coupons.'],
          [
            'create-edit',
            'Create and edit',
            'Creates and updates coupon details.',
          ],
          ['presets', 'Presets', 'Applies common discount templates.'],
          ['pagination', 'Pagination', 'Pages through coupons.'],
          [
            'delete-confirmation',
            'Delete confirmation',
            'Confirms destructive deletion.',
          ],
          ['usage-data', 'Usage data', 'Shows coupon redemption metrics.'],
        ],
        'enabled',
        { protected: true },
      ),
      page(
        'vendor-app',
        'vendor-support',
        'Support',
        '/support',
        'Vendor support ticket creation and history.',
        [
          ['ticket-history', 'Ticket history', 'Lists vendor tickets.'],
          ['create-ticket', 'Create ticket', 'Submits new support tickets.'],
          ['validation', 'Validation', 'Validates subject and message.'],
          ['feedback', 'Feedback', 'Shows success and API errors.'],
        ],
        'enabled',
        { protected: true },
      ),
      page(
        'vendor-app',
        'vendor-reviews',
        'Reviews',
        '/reviews',
        'Vendor customer review management.',
        [
          ['review-list', 'Review list', 'Displays product and store reviews.'],
          [
            'rating-summary',
            'Rating summary',
            'Summarizes average rating and counts.',
          ],
          ['filters', 'All, low, and recent filters', 'Filters review views.'],
        ],
        'enabled',
        { protected: true },
      ),
      page(
        'vendor-app',
        'vendor-notifications',
        'Notifications',
        '/notifications',
        'Vendor notification inbox.',
        [
          [
            'notification-list',
            'Notification list',
            'Displays vendor notifications.',
          ],
          ['filter', 'Filter', 'Filters read and unread notifications.'],
          ['mark-read', 'Mark read', 'Marks one notification read.'],
          ['mark-all-read', 'Mark all read', 'Marks all notifications read.'],
        ],
        'enabled',
        { protected: true },
      ),
      page(
        'vendor-app',
        'vendor-store-settings',
        'Store Settings',
        '/store-settings',
        'Store profile, hours, delivery, and status settings.',
        [
          [
            'profile-form',
            'Profile form',
            'Updates store display and business details.',
          ],
          ['business-hours', 'Business hours', 'Configures opening schedule.'],
          ['map-fields', 'Map fields', 'Captures location and coordinates.'],
          [
            'delivery-settings',
            'Delivery settings',
            'Controls order and delivery configuration.',
          ],
          [
            'status-controls',
            'Status controls',
            'Controls accepting orders state.',
          ],
          ['save-settings', 'Save settings', 'Persists store configuration.'],
        ],
        'enabled',
        { protected: true },
      ),
    ],
  },
  {
    id: 'delivery-app',
    name: 'Delivery App',
    description:
      'Delivery partner workspace for assignments, active delivery, earnings, and profile management.',
    icon: 'DA',
    color: 'blue',
    pages: [
      page(
        'delivery-app',
        'delivery-login',
        'Login',
        '/login',
        'Delivery partner authentication.',
        [
          [
            'credential-login',
            'Credential login',
            'Username and password login.',
          ],
          [
            'auth-errors',
            'Authentication errors',
            'Shows invalid credential and session errors.',
          ],
        ],
      ),
      page(
        'delivery-app',
        'delivery-change-password',
        'Change Password',
        '/change-password',
        'Delivery partner password update.',
        [
          [
            'current-password',
            'Current password validation',
            'Validates existing password.',
          ],
          [
            'new-password',
            'New password validation',
            'Validates new password and confirmation.',
          ],
        ],
        'enabled',
        { protected: true },
      ),
      page(
        'delivery-app',
        'delivery-dashboard',
        'Dashboard',
        '/',
        'Partner operational dashboard.',
        [
          ['stats', 'Stats', 'Shows delivery and earning metrics.'],
          [
            'active-assignments',
            'Active assignments',
            'Shows current accepted work.',
          ],
          [
            'availability-toggle',
            'Availability toggle',
            'Controls partner availability.',
          ],
          ['geo-updates', 'Geolocation updates', 'Updates partner location.'],
        ],
        'enabled',
        { protected: true },
      ),
      page(
        'delivery-app',
        'delivery-available',
        'Available Orders',
        '/available',
        'Available delivery request queue.',
        [
          [
            'poll-refresh',
            'Poll and refresh requests',
            'Refreshes available assignments.',
          ],
          ['accept-reject', 'Accept or reject', 'Responds to delivery offers.'],
          [
            'vendor-map',
            'Vendor map and navigation',
            'Shows vendor pickup location.',
          ],
        ],
        'enabled',
        { protected: true },
      ),
      page(
        'delivery-app',
        'delivery-active',
        'Active Delivery',
        '/active',
        'Active delivery execution screen.',
        [
          ['poll-active', 'Poll active', 'Refreshes current assignment.'],
          ['live-map', 'Live map', 'Shows delivery route context.'],
          ['location-updates', 'Location updates', 'Sends driver location.'],
          [
            'navigate',
            'Navigate vendor or customer',
            'Launches navigation links.',
          ],
          ['on-the-way', 'Mark on the way', 'Updates delivery status.'],
          ['cancel-assignment', 'Cancel assignment', 'Cancels when allowed.'],
          ['payment-qr', 'Payment QR', 'Supports payment collection flow.'],
          [
            'otp-photo',
            'OTP and photo confirmation',
            'Confirms pickup or delivery proof.',
          ],
        ],
        'enabled',
        { protected: true },
      ),
      page(
        'delivery-app',
        'delivery-history',
        'History',
        '/history',
        'Completed and cancelled delivery history.',
        [
          ['history-list', 'History list', 'Lists past assignments.'],
          [
            'earnings-per-delivery',
            'Earnings per delivery',
            'Shows per-order earnings.',
          ],
          ['status-display', 'Status display', 'Displays delivery outcome.'],
        ],
        'enabled',
        { protected: true },
      ),
      page(
        'delivery-app',
        'delivery-earnings',
        'Earnings',
        '/earnings',
        'Partner earnings and payout history.',
        [
          ['summary', 'Summary', 'Shows earning totals.'],
          ['payout-list', 'Payout list', 'Lists payout records.'],
          [
            'approve-decline',
            'Approve or decline',
            'Handles payout review actions.',
          ],
          ['verify-credited', 'Verify credited', 'Confirms payout credit.'],
        ],
        'enabled',
        { protected: true },
      ),
      page(
        'delivery-app',
        'delivery-profile',
        'Profile',
        '/profile',
        'Partner profile and base location settings.',
        [
          ['load-profile', 'Load profile', 'Loads partner profile.'],
          ['save-profile', 'Save profile', 'Persists profile changes.'],
          ['base-location', 'Base location', 'Stores default operating area.'],
          ['coordinates', 'Coordinates', 'Captures latitude and longitude.'],
        ],
        'enabled',
        { protected: true },
      ),
    ],
  },
  {
    id: 'customer-app',
    name: 'Customer App',
    description:
      'Customer shopping web app for discovery, cart, checkout, orders, wallet, help, and account flows.',
    icon: 'CA',
    color: 'orange',
    pages: [
      page(
        'customer-app',
        'customer-home',
        'Home',
        '/',
        'Customer storefront landing page.',
        [
          ['banners', 'Banners', 'Shows marketing banners.'],
          ['categories', 'Categories', 'Displays shopping categories.'],
          ['nearby-stores', 'Nearby stores', 'Lists nearby vendors.'],
          ['featured-products', 'Featured products', 'Highlights products.'],
          ['mini-cart', 'Mini cart', 'Shows cart summary.'],
          [
            'location-content',
            'Location content',
            'Adapts content by location.',
          ],
        ],
      ),
      page(
        'customer-app',
        'customer-stores',
        'Stores',
        '/stores',
        'Store browsing page.',
        [
          ['browse', 'Browse stores', 'Lists available stores.'],
          ['category-filter', 'Category filter', 'Filters stores by category.'],
          ['sort', 'Sort', 'Sorts store results.'],
          ['search', 'Search', 'Searches store names.'],
          ['load-more', 'Load more', 'Paginates store results.'],
        ],
      ),
      page(
        'customer-app',
        'customer-category',
        'Category',
        '/category/:id',
        'Category-specific product and store listing.',
        [
          [
            'category-listing',
            'Category listing',
            'Loads stores and products for the selected category.',
          ],
        ],
      ),
      page(
        'customer-app',
        'customer-store-detail',
        'Store Detail',
        '/store/:id',
        'Storefront detail and in-store shopping.',
        [
          ['store-profile', 'Store profile', 'Shows vendor details.'],
          [
            'in-store-search',
            'In-store search',
            'Searches within store products.',
          ],
          ['category-filter', 'Category filter', 'Filters store products.'],
          ['sort', 'Sort', 'Sorts products.'],
          ['add-to-cart', 'Add to cart', 'Adds product to cart.'],
        ],
      ),
      page(
        'customer-app',
        'customer-product-detail',
        'Product Detail',
        '/product/:id',
        'Product information and cart actions.',
        [
          ['detail-load', 'Detail load', 'Loads product data.'],
          [
            'variant-size',
            'Variant and size select',
            'Chooses product options.',
          ],
          ['quantity', 'Quantity', 'Controls quantity.'],
          ['add-buy', 'Add or buy now', 'Adds to cart or checks out.'],
          ['wishlist', 'Wishlist', 'Saves product.'],
        ],
      ),
      page(
        'customer-app',
        'customer-search',
        'Search',
        '/search',
        'Global customer search.',
        [
          ['global-search', 'Global search', 'Searches stores and products.'],
          ['result-tabs', 'Result tabs', 'Switches search result types.'],
          ['quick-filters', 'Quick filters', 'Applies common filters.'],
          ['filter-drawer', 'Filter drawer', 'Opens advanced filters.'],
        ],
      ),
      page(
        'customer-app',
        'customer-cart',
        'Cart',
        '/cart',
        'Shopping cart and coupon flow.',
        [
          ['cart-view', 'Cart view', 'Displays cart items.'],
          ['quantity-update', 'Quantity update', 'Updates item quantity.'],
          ['remove-items', 'Remove items', 'Removes cart lines.'],
          ['save-later', 'Save for later', 'Moves products out of cart.'],
          ['coupon-apply', 'Coupon apply', 'Applies discounts.'],
          ['checkout', 'Checkout', 'Navigates to checkout.'],
        ],
        'enabled',
        { protected: true },
      ),
      page(
        'customer-app',
        'customer-checkout',
        'Checkout',
        '/checkout',
        'Order placement and payment page.',
        [
          ['address-select', 'Address select', 'Chooses delivery address.'],
          ['fee-preview', 'Fee preview', 'Shows charges before order.'],
          [
            'payment-method',
            'Payment method and UPI',
            'Selects payment option.',
          ],
          ['scheduled-slot', 'Scheduled slot', 'Chooses delivery slot.'],
          ['coupon', 'Coupon', 'Applies coupon.'],
          ['cod-confirmation', 'COD confirmation', 'Confirms cash orders.'],
          ['place-order', 'Place order', 'Submits order.'],
        ],
        'enabled',
        { protected: true },
      ),
      page(
        'customer-app',
        'customer-orders',
        'Orders',
        '/orders',
        'Customer order list.',
        [
          ['order-list', 'Order list', 'Lists orders.'],
          ['total-spent', 'Total spent', 'Shows spend summary.'],
          ['status-display', 'Status display', 'Shows lifecycle state.'],
          [
            'tracking-links',
            'Tracking and detail links',
            'Opens order details or tracking.',
          ],
        ],
        'enabled',
        { protected: true },
      ),
      page(
        'customer-app',
        'customer-tracking',
        'Tracking',
        '/tracking/:id',
        'Order tracking and timeline.',
        [
          ['live-map', 'Live map', 'Shows live delivery map.'],
          ['timeline', 'Timeline', 'Displays order events.'],
          ['payment-status', 'Payment status', 'Shows payment state.'],
          ['invoice', 'Invoice', 'Downloads invoice.'],
          [
            'wallet-navigation',
            'Wallet navigation',
            'Links to wallet actions.',
          ],
        ],
        'enabled',
        { protected: true },
      ),
      page(
        'customer-app',
        'customer-order-finished',
        'Order Finished',
        '/order-finished/:id',
        'Post-order completion experience.',
        [
          ['summary', 'Summary', 'Shows completed order summary.'],
          ['items', 'Items', 'Lists purchased items.'],
          ['rating-submit', 'Rating submit', 'Captures review.'],
          ['invoice', 'Invoice', 'Downloads invoice.'],
          ['offers', 'Offers', 'Shows follow-up offers.'],
        ],
        'enabled',
        { protected: true },
      ),
      page(
        'customer-app',
        'customer-help',
        'Help and Issues',
        '/help',
        'Customer help entry and issue messaging.',
        [
          ['create-issue', 'Create support issue', 'Starts issue ticket.'],
          ['issue-type', 'Issue type', 'Chooses issue category.'],
          ['messages', 'Send messages', 'Sends support chat messages.'],
          [
            'existing-thread',
            'Existing issue thread',
            'Loads ongoing issue conversation.',
          ],
        ],
        'enabled',
        { protected: true },
      ),
      page(
        'customer-app',
        'customer-profile',
        'Profile',
        '/profile',
        'Customer profile and account shortcuts.',
        [
          ['account-summary', 'Account summary', 'Shows profile details.'],
          [
            'wallet-referral',
            'Wallet and referral preview',
            'Shows quick finance and referral info.',
          ],
          ['recent-activity', 'Recent activity', 'Shows recent orders.'],
          [
            'membership',
            'Membership placeholder',
            'Shows loyalty or membership entry.',
          ],
          ['shortcuts', 'Shortcuts', 'Links to account pages.'],
        ],
        'enabled',
        { protected: true },
      ),
      page(
        'customer-app',
        'customer-addresses',
        'Addresses',
        '/addresses',
        'Customer address book.',
        [
          ['list', 'List', 'Shows addresses.'],
          ['add-edit', 'Add and edit modal', 'Creates or edits addresses.'],
          ['delete', 'Delete', 'Removes address.'],
          ['make-default', 'Make default', 'Sets default address.'],
          ['select-address', 'Select address', 'Chooses address for checkout.'],
        ],
        'enabled',
        { protected: true },
      ),
      page(
        'customer-app',
        'customer-offers',
        'Offers',
        '/offers',
        'Available customer promotions.',
        [
          ['offer-list', 'Offer list', 'Displays deals.'],
          ['apply-coupon', 'Apply coupon', 'Applies a selected coupon.'],
        ],
      ),
      page(
        'customer-app',
        'customer-wallet',
        'Wallet',
        '/wallet',
        'Customer wallet and transactions.',
        [
          ['balance', 'Balance', 'Shows wallet balance.'],
          ['transactions', 'Transactions', 'Lists wallet activity.'],
          ['razorpay-topup', 'Razorpay top-up', 'Starts top-up payment.'],
          ['verify-topup', 'Verify top-up', 'Verifies payment result.'],
        ],
        'enabled',
        { protected: true },
      ),
      page(
        'customer-app',
        'customer-wishlist',
        'Wishlist',
        '/wishlist',
        'Saved products.',
        [
          ['saved-products', 'Saved products', 'Lists wishlist items.'],
          ['remove', 'Remove', 'Removes saved products.'],
          [
            'product-navigation',
            'Product navigation',
            'Opens product details.',
          ],
        ],
        'enabled',
        { protected: true },
      ),
      page(
        'customer-app',
        'customer-referral',
        'Referral',
        '/referral',
        'Customer referral rewards.',
        [
          [
            'referral-code',
            'Referral code and rewards',
            'Shows referral code and reward status.',
          ],
          ['copy-share', 'Copy or share link', 'Shares invitation.'],
        ],
        'enabled',
        { protected: true },
      ),
      page(
        'customer-app',
        'customer-issues',
        'Issues',
        '/issues',
        'Customer issue list.',
        [
          ['issue-list', 'List customer issues', 'Displays issue tickets.'],
          ['status', 'Status', 'Shows support status.'],
          ['open-details', 'Open details', 'Opens issue thread.'],
        ],
        'enabled',
        { protected: true },
      ),
    ],
  },
  {
    id: 'mobile-customer',
    name: 'Mobile Customer',
    description:
      'Mobile customer app screens for shopping, checkout, orders, support, wallet, and profile.',
    icon: 'MC',
    color: 'purple',
    pages: [
      page(
        'mobile-customer',
        'mobile-splash',
        'Splash',
        'Splash',
        'Mobile boot and health loading screen.',
        [
          ['boot-health', 'Boot health', 'Checks startup readiness.'],
          ['loading', 'Loading state', 'Shows app loading experience.'],
        ],
      ),
      page(
        'mobile-customer',
        'mobile-home',
        'Home',
        'Home',
        'Mobile home shopping experience.',
        [
          ['banners', 'Banners', 'Displays promos.'],
          ['nearby-vendors', 'Nearby vendors', 'Lists nearby shops.'],
          ['categories', 'Categories', 'Displays category shortcuts.'],
          [
            'top-picks',
            'Top picks cart',
            'Highlights products and cart state.',
          ],
          ['reorder', 'Reorder', 'Promotes recent orders.'],
          [
            'notification-sheet',
            'Notification sheet',
            'Shows notification drawer.',
          ],
        ],
      ),
      page(
        'mobile-customer',
        'mobile-search',
        'Search',
        'Search',
        'Mobile global search.',
        [
          ['search', 'Search', 'Searches catalog and stores.'],
          ['history', 'History', 'Displays recent searches.'],
          [
            'navigation',
            'Category, store, and product navigation',
            'Opens selected results.',
          ],
        ],
      ),
      page(
        'mobile-customer',
        'mobile-shops',
        'Shops',
        'Shops',
        'Mobile nearby shop browsing.',
        [
          ['nearby-stores', 'Nearby stores', 'Lists stores.'],
          ['location-change', 'Location change', 'Changes delivery location.'],
          ['filters', 'Filters', 'Filters shops.'],
          ['sort-sheet', 'Sort sheet', 'Sorts results.'],
          ['reset-filters', 'Reset filters', 'Clears filters.'],
        ],
      ),
      page(
        'mobile-customer',
        'mobile-shop-detail',
        'Shop Detail',
        'ShopDetail',
        'Mobile shop detail and product browsing.',
        [
          ['store-details', 'Store details', 'Shows shop profile.'],
          ['in-store-search', 'In-store search', 'Searches within shop.'],
          [
            'category-filters',
            'Category and filter controls',
            'Filters product groups.',
          ],
          ['expand-groups', 'Expand product groups', 'Expands categories.'],
          ['add-product', 'Add product', 'Adds items.'],
          ['update-quantity', 'Update quantity', 'Changes quantities.'],
          [
            'replace-cart',
            'Replace cart',
            'Handles cross-store cart replacement.',
          ],
        ],
      ),
      page(
        'mobile-customer',
        'mobile-products',
        'Products',
        'Products',
        'Legacy mobile product-list route that redirects customers into store or search product discovery.',
        [
          [
            'redirect',
            'Product discovery redirect',
            'Moves legacy product-list navigation into supported discovery screens.',
          ],
        ],
        'enabled',
        { redirected: true },
      ),
      page(
        'mobile-customer',
        'mobile-product-detail',
        'Product Detail',
        'ProductDetail',
        'Mobile product detail.',
        [
          ['load-product', 'Load product', 'Loads product data.'],
          ['quantity', 'Quantity selection', 'Chooses quantity.'],
          ['add-cart', 'Add to cart', 'Adds product.'],
          [
            'replace-cart',
            'Replace cart handling',
            'Handles cross-store cart.',
          ],
          ['favorite', 'Favorite toggle', 'Saves product.'],
        ],
      ),
      page(
        'mobile-customer',
        'mobile-cart',
        'Cart',
        'Cart',
        'Mobile cart screen.',
        [
          ['load-cart', 'Load cart', 'Loads cart contents.'],
          ['update-quantities', 'Update quantities', 'Changes quantities.'],
          ['remove-items', 'Remove items', 'Removes lines.'],
          ['suggestions', 'Suggestions', 'Shows recommendations.'],
          ['checkout', 'Checkout', 'Navigates to checkout.'],
        ],
        'enabled',
        { protected: true },
      ),
      page(
        'mobile-customer',
        'mobile-checkout',
        'Checkout',
        'Checkout',
        'Mobile checkout.',
        [
          ['address-selection', 'Address selection', 'Selects address.'],
          ['fee-preview', 'Fee preview', 'Shows fees.'],
          ['schedule-slots', 'Schedule slots', 'Chooses slot.'],
          [
            'far-delivery-ack',
            'Far delivery acknowledgement',
            'Captures long-distance confirmation.',
          ],
          ['payment', 'Payment', 'Selects and processes payment.'],
          ['coupon', 'Coupon', 'Applies coupon.'],
          ['wallet-amount', 'Wallet amount', 'Uses wallet balance.'],
          ['loyalty', 'Loyalty', 'Shows loyalty controls.'],
          ['place-order', 'Place order', 'Submits order.'],
        ],
        'enabled',
        { protected: true },
      ),
      page(
        'mobile-customer',
        'mobile-orders',
        'Orders',
        'Orders',
        'Mobile order history.',
        [
          ['tabs', 'Active, past, and cancelled tabs', 'Filters order groups.'],
          ['load-orders', 'Load orders', 'Loads order list.'],
          ['reorder', 'Reorder', 'Repeats prior order.'],
          ['details', 'Details', 'Opens order detail.'],
          ['tracking', 'Tracking', 'Opens order tracking.'],
        ],
        'enabled',
        { protected: true },
      ),
      page(
        'mobile-customer',
        'mobile-order-detail',
        'Order Detail',
        'OrderDetail',
        'Mobile order detail.',
        [
          ['summary', 'Summary', 'Shows order summary.'],
          [
            'cancellation-policy',
            'Cancellation policy',
            'Explains cancelability.',
          ],
          ['cancel', 'Cancel', 'Cancels when allowed.'],
          ['call-contact', 'Call contact', 'Starts phone call.'],
          ['pay-now', 'Pay now and verify', 'Starts and verifies payment.'],
          ['show-all-items', 'Show all items', 'Expands item list.'],
          ['help', 'Help', 'Opens support flow.'],
        ],
        'enabled',
        { protected: true },
      ),
      page(
        'mobile-customer',
        'mobile-order-tracking',
        'Order Tracking',
        'OrderTracking',
        'Mobile live tracking screen.',
        [
          ['timeline', 'Order and tracking timeline', 'Displays order events.'],
          [
            'driver-location',
            'Live socket driver location',
            'Receives driver position.',
          ],
          ['map-status', 'Map and status', 'Shows map and current state.'],
        ],
        'enabled',
        { protected: true },
      ),
      page(
        'mobile-customer',
        'mobile-order-help',
        'Order Help',
        'OrderHelp',
        'Mobile support issue category picker.',
        [['issue-category', 'Issue category picker', 'Chooses help category.']],
        'enabled',
        { protected: true },
      ),
      page(
        'mobile-customer',
        'mobile-order-issue',
        'Order Issue',
        'OrderIssue',
        'Mobile support thread and issue creation.',
        [
          ['create-issue', 'Create issue', 'Creates support issue.'],
          ['attach-photo', 'Attach photo', 'Uploads evidence.'],
          ['thread-load', 'Thread load', 'Loads existing messages.'],
          [
            'live-socket',
            'Live issue socket',
            'Receives live support updates.',
          ],
          ['send-messages', 'Send messages', 'Sends chat messages.'],
          ['upload-attachments', 'Upload attachments', 'Uploads files.'],
        ],
        'enabled',
        { protected: true },
      ),
      page(
        'mobile-customer',
        'mobile-order-rating',
        'Order Rating',
        'OrderRating',
        'Post-order rating screen.',
        [
          ['submit-rating', 'Submit rating', 'Submits order rating.'],
          ['shop-rating', 'Shop rating', 'Captures store rating.'],
          ['tip-review', 'Tip and review', 'Captures review details.'],
        ],
        'enabled',
        { protected: true },
      ),
      page(
        'mobile-customer',
        'mobile-my-issues',
        'My Issues',
        'MyIssues',
        'Mobile issue list.',
        [
          ['list-threads', 'List issue threads', 'Displays support threads.'],
          ['open-thread', 'Open issue thread', 'Navigates to messages.'],
        ],
        'enabled',
        { protected: true },
      ),
      page(
        'mobile-customer',
        'mobile-set-location',
        'Set Location',
        'SetLocation',
        'Mobile location selection.',
        [
          ['search-map', 'Search map location', 'Searches map places.'],
          ['suggestions', 'Suggestions', 'Shows address suggestions.'],
          ['current-location', 'Current location', 'Uses device location.'],
          ['pick-coordinate', 'Pick coordinate', 'Selects map coordinate.'],
          ['reverse-geocode', 'Reverse geocode', 'Resolves address.'],
          ['save', 'Save', 'Stores selected location.'],
        ],
      ),
      page(
        'mobile-customer',
        'mobile-addresses',
        'Addresses',
        'Addresses',
        'Mobile address book.',
        [
          ['load', 'Load', 'Loads addresses.'],
          ['add-edit', 'Add or edit', 'Creates or edits address.'],
          [
            'select-share-remove',
            'Select, share, and remove',
            'Controls address actions.',
          ],
          [
            'map-geocode',
            'Map, geocode, and current location',
            'Uses map and location services.',
          ],
        ],
        'enabled',
        { protected: true },
      ),
      page(
        'mobile-customer',
        'mobile-wallet',
        'Wallet',
        'Wallet',
        'Mobile wallet and loyalty.',
        [
          ['wallet-loyalty', 'Wallet and loyalty', 'Shows balances.'],
          ['topup-presets', 'Top-up presets', 'Provides quick amounts.'],
          [
            'razorpay-verify',
            'Razorpay top-up verify',
            'Verifies top-up payment.',
          ],
          ['transactions', 'Transactions', 'Lists wallet transactions.'],
        ],
        'enabled',
        { protected: true },
      ),
      page(
        'mobile-customer',
        'mobile-wishlist',
        'Wishlist',
        'Wishlist',
        'Mobile wishlist.',
        [
          ['load', 'Load', 'Loads wishlist.'],
          ['remove', 'Remove', 'Removes item.'],
          ['open-product', 'Open product', 'Opens product detail.'],
        ],
        'enabled',
        { protected: true },
      ),
      page(
        'mobile-customer',
        'mobile-referral',
        'Referral',
        'Referral',
        'Mobile referral screen.',
        [
          ['fetch-referral', 'Fetch referral', 'Loads referral code.'],
          [
            'validate-apply',
            'Validate and apply code',
            'Applies referral code.',
          ],
          ['share-invite', 'Share invite', 'Shares invite.'],
        ],
        'enabled',
        { protected: true },
      ),
      page(
        'mobile-customer',
        'mobile-profile',
        'Profile',
        'Profile',
        'Mobile account profile.',
        [
          [
            'guest-account',
            'Guest and account profile',
            'Shows logged-in or guest state.',
          ],
          ['save-profile', 'Save profile', 'Updates account details.'],
          ['avatar', 'Avatar', 'Updates avatar.'],
          ['shortcuts', 'Shortcuts', 'Shows account links.'],
          ['logout-login', 'Logout or login', 'Handles session actions.'],
        ],
        'enabled',
        { protected: true },
      ),
      page(
        'mobile-customer',
        'mobile-login',
        'Login',
        'Login',
        'Mobile login screen.',
        [
          [
            'customer-login',
            'Customer login',
            'Authenticates mobile customer.',
          ],
        ],
      ),
      page(
        'mobile-customer',
        'mobile-register',
        'Register',
        'Register',
        'Mobile registration screen.',
        [['registration', 'Registration', 'Creates customer account.']],
      ),
      page(
        'mobile-customer',
        'mobile-forgot-password',
        'Forgot Password',
        'ForgotPassword',
        'Password reset request.',
        [
          [
            'request-reset',
            'Request reset email',
            'Sends reset email or token.',
          ],
        ],
      ),
      page(
        'mobile-customer',
        'mobile-reset-password',
        'Reset Password',
        'ResetPassword',
        'Password reset submission.',
        [['submit-reset', 'Submit token and new password', 'Resets password.']],
      ),
      page(
        'mobile-customer',
        'mobile-offers',
        'Offers',
        'Offers',
        'Mobile offers screen.',
        [
          ['load-deals', 'Load deals', 'Loads available deals.'],
          ['apply-deals', 'Apply deals', 'Applies offer to cart.'],
        ],
      ),
      page(
        'mobile-customer',
        'mobile-not-found',
        'Not Found',
        'NotFound',
        'Mobile fallback screen.',
        [
          [
            'fallback-shortcuts',
            'Fallback shortcuts',
            'Provides navigation back into app.',
          ],
        ],
      ),
    ],
  },
];
